app:
    resource: '@AppBundle/Controller/'
    type: annotation

# app/config/routing.yml
#pagina:
#    path: /sitio/{nombrePagina}/
#    defaults:
#        _controller: 'AppBundle:Default:pagina'
#    requirements:
#        nombrePagina: ayuda|privacidad|sobre_nosotros